import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

// pgTable('table_name', { columns }) defines a table
// The first argument is the actual table name in your database
// The second argument is an object where each key is a column

// ---------------------------------------------------------
// THREADS TABLE
// A thread = one conversation (like a chat session)
// One user can have many threads
// ---------------------------------------------------------
export const threads = pgTable("chat_threads", {
  // uuid is a unique ID — automatically generated by the database
  // .primaryKey() means this is the unique identifier for each row
  // .defaultRandom() means Postgres generates a random UUID for us
  id: uuid("id").primaryKey().defaultRandom(),

  // The title of the conversation — we'll generate this from the first message
  // .notNull() means this column must always have a value
  title: text("title").notNull(),

  // When this thread was created
  // .defaultNow() means Postgres automatically sets this to the current time
  createdAt: timestamp("created_at").defaultNow().notNull(),

  // When this thread was last updated — we'll update this every time
  // a new message is added to the thread
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// ---------------------------------------------------------
// MESSAGES TABLE
// A message = one chat bubble (either user or AI)
// One thread can have many messages
// ---------------------------------------------------------
export const messages = pgTable("chat_messages", {
  // Each message has its own unique ID
  id: uuid("id").primaryKey().defaultRandom(),

  // Which thread this message belongs to
  // This is a "foreign key" — it references the id column in threads table
  // Every message MUST belong to a thread
  threadId: uuid("thread_id")
    .notNull()
    .references(() => threads.id, {
      // If the thread is deleted, delete all its messages too
      // This is called "cascade delete" — children follow the parent
      onDelete: "cascade",
    }),

  // Who sent this message — either 'user' or 'assistant'
  // text() is just a string column in Postgres
  role: text("role", { enum: ["user", "assistant"] }).notNull(),

  // The actual message content
  content: text("content").notNull(),

  // When this message was created — useful for ordering messages correctly
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Export TypeScript types inferred directly from your schema
// This means your types and your database are always in sync —
// if you change the schema, the types update automatically
export type Thread = typeof threads.$inferSelect;
export type NewThread = typeof threads.$inferInsert;
export type Message = typeof messages.$inferSelect;
export type NewMessage = typeof messages.$inferInsert;
